const constants = {
    EXPAND_PROCESS: 'EXPAND_PROCESS',
    START_PROCESS: 'START_PROCESS',
    STOP_PROCESS: 'STOP_PROCESS',
    UPDATE_PROCESS: 'UPDATE_PROCESS',
    SELECT_ACCOUNT_TYPE: 'SELECT_ACCOUNT_TYPE',
    SELECT_ACCOUNT: 'SELECT_ACCOUNT',
    LOG: 'LOG',
    CLEAR_LOG: 'CLEAR_LOG',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    CREATE_POST: 'CREATE_POST',
    UPDATE_POST: 'UPDATE_POST',
    SCHEDULE_POST: 'SCHEDULE_POST',
    DELETE_POST: 'DELETE_POST',
    CREATE_CAPTION: 'CREATE_CAPTION',
    DELETE_CAPTION: 'DELETE_CAPTION',
    CREATE_COMMENT: 'CREATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    RESET: 'RESET'
}

export default constants;